import type {Metadata} from 'next';

export const SITE_URL = 'https://www.byteoperator.com';
export const SITE_NAME = 'Byte Operator';

// Generated by app/opengraph-image.tsx. Listed explicitly because a page that
// sets its own `openGraph` / `twitter` object drops the inherited image.
const SHARE_IMAGE = {
  url: '/opengraph-image',
  width: 1200,
  height: 630,
  alt: 'Byte Operator – The Software Agency That Drives Real Growth',
};

type PageMetadataInput = {
  title: string;
  description: string;
  /** Path of the canonical URL, e.g. `/about`. */
  path: string;
  type?: 'website' | 'article';
  publishedTime?: string;
  robots?: Metadata['robots'];
  keywords?: string[];
};

/**
 * Page metadata with canonical, Open Graph and Twitter tags that all agree.
 *
 * Next.js replaces (rather than merges) a parent's `openGraph` / `twitter`
 * objects, so every page must set its own url, title and description here or
 * it inherits the homepage's.
 */
export function pageMetadata({
  title,
  description,
  path,
  type = 'website',
  publishedTime,
  robots,
  keywords,
}: PageMetadataInput): Metadata {
  const url = path === '/' ? SITE_URL : `${SITE_URL}${path}`;

  return {
    title,
    description,
    ...(keywords ? {keywords} : {}),
    ...(robots ? {robots} : {}),
    alternates: {canonical: url},
    openGraph: {
      title,
      description,
      url,
      siteName: SITE_NAME,
      locale: 'en_US',
      type,
      images: [SHARE_IMAGE],
      ...(publishedTime ? {publishedTime} : {}),
    },
    twitter: {
      card: 'summary_large_image',
      title,
      description,
      images: [SHARE_IMAGE],
    },
  };
}
